# Generated by Django 3.2.9 on 2021-12-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commits',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=128)),
                ('repo_name', models.CharField(max_length=128)),
                ('con_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=128)),
                ('repo_name', models.CharField(max_length=128)),
                ('con_name', models.CharField(max_length=128)),
                ('con_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_newest', models.DateTimeField()),
            ],
        ),
    ]
